name: Config Generator

on:
  push:
    branches:
      - main
    paths:
      - 'anomaly-rules/*.yaml'

jobs:
  generate_config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          python3 -m pip install -r requirements.txt
        fi

    - name: Run Python script
      run: python3 scripts/config_generator.py

    - name: Commit and push config.yaml
      run: |
        git config user.name github-actions
        git config user.email github@users.noreply.github.com
        git add .
        git commit -m "Genereate text file"
        git push
