name: 'Push to master'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # the checkout action persists the passed credentials by default
    # subsequent git commands will pick them up automatically
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PUSH_TOKEN}}
    - run: |
        echo "Pushing generated result..."
        cd outputs
        date > generated.txt
        git config user.name github-actions
        git config user.email github@users.noreply.github.com
        git add .
        git commit -m "Genereate text file"
        git push